"""Fix scheduled_date column typo

Revision ID: 65fe02999c72
Revises: 7c58f81153a7
Create Date: 2026-07-07 01:41:29.926143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fe02999c72'
down_revision: Union[str, Sequence[str], None] = '7c58f81153a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_date', sa.Date(), nullable=False))
    op.drop_column('tasks', 'schedule_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('schedule_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'scheduled_date')
    # ### end Alembic commands ###